// home
export const FETCH_HOME_REQUEST = 'FETCH_HOME_REQUEST';
export const FETCH_HOME_SUCCESS = 'FETCH_HOME_SUCCESS';
export const FETCH_HOME_FAILURE = 'FETCH_HOME_FAILURE';

// location
export const FETCH_LOCATION_REQUEST = 'FETCH_LOCATION_REQUEST';
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';
export const FETCH_LOCATION_FAILURE = 'FETCH_LOCATION_FAILURE';

// register
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE';
export const OTP_RESEND_REQUEST = 'OTP_RESEND_REQUEST';
export const OTP_RESEND_SUCCESS = 'OTP_RESEND_SUCCESS';
export const OTP_RESEND_FAILURE = 'OTP_RESEND_FAILURE';
export const SET_SIGNUP_PAGE = 'SET_SIGNUP_PAGE';

// authentication
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const GENERAL_CHECK_REQUEST = 'GENERAL_CHECK_REQUEST';
export const GENERAL_CHECK_SUCCESS = 'GENERAL_CHECK_SUCCESS';
export const GENERAL_CHECK_FAILURE = 'GENERAL_CHECK_FAILURE';
export const AUTHENTICATED_CHECK_REQUEST = 'AUTHENTICATED_CHECK_REQUEST';
export const AUTHENTICATED_CHECK_SUCCESS = 'AUTHENTICATED_CHECK_SUCCESS';
export const AUTHENTICATED_CHECK_FAILURE = 'AUTHENTICATED_CHECK_FAILURE';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_NOT_LOGGED_IN = 'USER_NOT_LOGGED_IN';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// recover account
export const ACCOUNT_RECOVERY_REQUEST = 'ACCOUNT_RECOVERY_REQUEST';
export const ACCOUNT_RECOVERY_SUCCESS = 'ACCOUNT_RECOVERY_SUCCESS';
export const ACCOUNT_RECOVERY_FAILURE = 'ACCOUNT_RECOVERY_FAILURE';
export const ACCOUNT_RECOVERY_VERIFY_OTP_REQUEST = 'ACCOUNT_RECOVERY_VEIRFY_OTP_REQUEST';
export const ACCOUNT_RECOVERY_VERIFY_OTP_SUCCESS = 'ACCOUNT_RECOVERY_VEIRFY_OTP_SUCCESS';
export const ACCOUNT_RECOVERY_VERIFY_OTP_FAILURE = 'ACCOUNT_RECOVERY_VEIRFY_OTP_FAILURE';
export const ACCOUNT_RECOVERY_OTP_RESEND_REQUEST = 'ACCOUNT_RECOVERY_OTP_RESEND_REQUEST';
export const ACCOUNT_RECOVERY_OTP_RESEND_SUCCESS = 'ACCOUNT_RECOVERY_OTP_RESEND_SUCCESS';
export const ACCOUNT_RECOVERY_OTP_RESEND_FAILURE = 'ACCOUNT_RECOVERY_OTP_RESEND_FAILURE';
export const ACCOUNT_RECOVERY_CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const ACCOUNT_RECOVERY_CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const ACCOUNT_RECOVERY_CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
export const SET_ACCOUNT_RECOVER_PAGE = 'SET_ACCOUNT_RECOVER_PAGE';

// photo upload
export const PHOTO_UPLOAD_REQUEST = 'PHOTO_UPLOAD_REQUEST';
export const PHOTO_UPLOAD_UPDATE_PROGRESS = 'PHOTO_UPLOAD_PROGRESS';
export const PHOTO_UPLOAD_SUCCESS = 'PHOTO_UPLOAD_SUCCESS';
export const PHOTO_UPLOAD_FAILURE = 'PHOTO_UPLOAD_FAILURE';

// create shop
export const CREATE_SHOP_REQUEST = 'CREATE_SHOP_REQUEST';
export const CREATE_SHOP_SUCCESS = 'CREATE_SHOP_SUCCESS';
export const CREATE_SHOP_FAILURE = 'CREATE_SHOP_FAILURE';

// create ad
export const CHECK_AUTH_CREATE_AD_REQUEST = 'CHECK_AUTH_CREATE_AD_REQUEST';
export const CHECK_AUTH_CREATE_AD_SUCCESS = 'CHECK_AUTH_CREATE_AD_SUCCESS';
export const CHECK_AUTH_CREATE_AD_FAILURE = 'CHECK_AUTH_CREATE_AD_FAILURE';

// create individual ad
export const CREATE_INDIVIDUAL_AD_REQUEST = 'CREATE_INDIVIDUAL_AD_REQUEST';
export const CREATE_INDIVIDUAL_AD_SUCCESS = 'CREATE_INDIVIDUAL_AD_SUCCESS';
export const CREATE_INDIVIDUAL_AD_FAILURE = 'CREATE_INDIVIDUAL_AD_FAILURE';

// attach ad
export const ATTACH_AD_REQUEST = 'ATTACH_AD_REQUEST';
export const ATTACH_AD_SUCCESS = 'ATTACH_AD_SUCCESS';
export const ATTACH_AD_FAILURE = 'ATTACH_AD_FAILURE';

//shops
export const FETCH_SHOPS_REQUEST = 'FETCH_SHOPS_REQUEST';
export const FETCH_SHOPS_SUCCESS = 'FETCH_SHOPS_SUCCESS';
export const FETCH_SHOPS_FAILURE = 'FETCH_SHOPS_FAILURE';
export const FETCH_AUTH_SHOP_REQUEST = 'FETCH_AUTH_SHOP_REQUEST';
export const FETCH_AUTH_SHOP_SUCCESS = 'FETCH_AUTH_SHOP_SUCCESS';
export const FETCH_AUTH_SHOP_FAILURE = 'FETCH_AUTH_SHOP_FAILURE';
export const CHECK_AUTH_UPDATE_SHOP_REQUEST = 'CHECK_AUTH_UPDATE_SHOP_REQUEST';
export const CHECK_AUTH_UPDATE_SHOP_SUCCESS = 'CHECK_AUTH_UPDATE_SHOP_SUCCESS';
export const CHECK_AUTH_UPDATE_SHOP_FAILURE = 'CHECK_AUTH_UPDATE_SHOP_FAILURE';

// ads
export const FETCH_ADS_REQUEST = 'FETCH_ADS_REQUEST';
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';
export const FETCH_ADS_FAILURE = 'FETCH_ADS_FAILURE';
export const CHECK_AUTH_UPDATE_AD_REQUEST = 'CHECK_AUTH_UPDATE_AD_REQUEST';
export const CHECK_AUTH_UPDATE_AD_SUCCESS = 'CHECK_AUTH_UPDATE_AD_SUCCESS';
export const CHECK_AUTH_UPDATE_AD_FAILURE = 'CHECK_AUTH_UPDATE_AD_FAILURE';

//individual ads
export const FETCH_INDIVIDUAL_ADS_REQUEST = 'FETCH_INDIVIDUAL_ADS_REQUEST';
export const FETCH_INDIVIDUAL_ADS_SUCCESS = 'FETCH_INDIVIDUAL_ADS_SUCCESS';
export const FETCH_INDIVIDUAL_ADS_FAILURE = 'FETCH_INDIVIDUAL_ADS_FAILURE';

// shop ads
export const FETCH_SHOP_ADS_REQUEST = 'FETCH_SHOP_ADS_REQUEST';
export const FETCH_SHOP_ADS_SUCCESS = 'FETCH_SHOP_ADS_SUCCESS';
export const FETCH_SHOP_ADS_FAILURE = 'FETCH_SHOP_ADS_FAILURE';

// shop details
export const FETCH_SHOP_REQUEST = "FETCH_SHOP_REQUEST";
export const FETCH_SHOP_SUCCESS = "FETCH_SHOP_SUCCESS";
export const FETCH_SHOP_FAILURE = "FETCH_SHOP_FAILURE";
export const RATE_SHOP_REQUEST = "RATE_SHOP_REQUEST";
export const RATE_SHOP_SUCCESS = "RATE_SHOP_SUCCESS";
export const RATE_SHOP_FAILURE = "RATE_SHOP_FAILURE";
export const SHOP_COMMENT_REQUEST = "SHOP_COMMENT_REQUEST";
export const SHOP_COMMENT_SUCCESS = "SHOP_COMMENT_SUCCESS";
export const SHOP_COMMENT_FAILURE = "SHOP_COMMENT_FAILURE";
export const SHOP_COMMENT_DELETE_REQUEST = "SHOP_COMMENT_DELETE_REQUEST";
export const SHOP_COMMENT_DELETE_SUCCESS = "SHOP_COMMENT_DELETE_SUCCESS";
export const SHOP_COMMENT_DELETE_FAILURE = "SHOP_COMMENT_DELETE_FAILURE";
export const SHOP_REPLY_REQUEST = "SHOP_REPLY_REQUEST";
export const SHOP_REPLY_SUCCESS = "SHOP_REPLY_SUCCESS";
export const SHOP_REPLY_FAILURE = "SHOP_REPLY_FAILURE";
export const SHOP_REPLY_DELETE_REQUEST = "SHOP_REPLY_DELETE_REQUEST";
export const SHOP_REPLY_DELETE_SUCCESS = "SHOP_REPLY_DELETE_SUCCESS";
export const SHOP_REPLY_DELETE_FAILURE = "SHOP_REPLY_DELETE_FAILURE";
export const SHOP_DELETE_REQUEST = "SHOP_DELETE_REQUEST";
export const SHOP_DELETE_SUCCESS = "SHOP_DELETE_SUCCESS";
export const SHOP_DELETE_FAILURE = "SHOP_DELETE_FAILURE";
export const TOGGLE_SHOP_STATUS_REQUEST = "TOGGLE_SHOP_STATUS_REQUEST";
export const TOGGLE_SHOP_STATUS_SUCCESS = "TOGGLE_SHOP_STATUS_SUCCESS";
export const TOGGLE_SHOP_STATUS_FAILURE = "TOGGLE_SHOP_STATUS_FAILURE";

// ad
export const FETCH_AD_REQUEST = 'FETCH_AD_REQUEST';
export const FETCH_AD_SUCCESS = 'FETCH_AD_SUCCESS';
export const FETCH_AD_FAILURE = 'FETCH_AD_FAILURE';
export const RATE_AD_REQUEST = "RATE_AD_REQUEST";
export const RATE_AD_SUCCESS = "RATE_AD_SUCCESS";
export const RATE_AD_FAILURE = "RATE_AD_FAILURE";
export const AD_COMMENT_REQUEST = "AD_COMMENT_REQUEST";
export const AD_COMMENT_SUCCESS = "AD_COMMENT_SUCCESS";
export const AD_COMMENT_FAILURE = "AD_COMMENT_FAILURE";
export const AD_COMMENT_DELETE_REQUEST = "AD_COMMENT_DELETE_REQUEST";
export const AD_COMMENT_DELETE_SUCCESS = "AD_COMMENT_DELETE_SUCCESS";
export const AD_COMMENT_DELETE_FAILURE = "AD_COMMENT_DELETE_FAILURE";
export const AD_REPLY_REQUEST = "AD_REPLY_REQUEST";
export const AD_REPLY_SUCCESS = "AD_REPLY_SUCCESS";
export const AD_REPLY_FAILURE = "AD_REPLY_FAILURE";
export const AD_REPLY_DELETE_REQUEST = "AD_REPLY_DELETE_REQUEST";
export const AD_REPLY_DELETE_SUCCESS = "AD_REPLY_DELETE_SUCCESS";
export const AD_REPLY_DELETE_FAILURE = "AD_REPLY_DELETE_FAILURE";
export const AD_DELETE_REQUEST = "AD_DELETE_REQUEST";
export const AD_DELETE_SUCCESS = "AD_DELETE_SUCCESS";
export const AD_DELETE_FAILURE = "AD_DELETE_FAILURE";
export const TOGGLE_AD_STATUS_REQUEST = "TOGGLE_AD_STATUS_REQUEST";
export const TOGGLE_AD_STATUS_SUCCESS = "TOGGLE_AD_STATUS_SUCCESS";
export const TOGGLE_AD_STATUS_FAILURE = "TOGGLE_AD_STATUS_FAILURE";
export const TOGGLE_FORCE_OPEN_REQUEST = "TOGGLE_FORCE_OPEN_REQUEST";
export const TOGGLE_FORCE_OPEN_SUCCESS = "TOGGLE_FORCE_OPEN_SUCCESS";
export const TOGGLE_FORCE_OPEN_FAILURE = "TOGGLE_FORCE_OPEN_FAILURE";

// auth ad
export const FETCH_AUTH_AD_REQUEST = 'FETCH_AUTH_AD_REQUEST';
export const FETCH_AUTH_AD_SUCCESS = 'FETCH_AUTH_AD_SUCCESS';
export const FETCH_AUTH_AD_FAILURE = 'FETCH_AUTH_AD_FAILURE';

//cart
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const AUTH_CHECK_CART_REQUEST = 'AUTH_CHECK_CART_REQUEST';
export const AUTH_CHECK_CART_SUCCESS = 'AUTH_CHECK_CART_SUCCESS';
export const AUTH_CHECK_CART_FAILURE = 'AUTH_CHECK_CART_FAILURE';
export const ADD_QUANTITY_TO_CART_REQUEST = 'ADD_QUANTITY_TO_CART_REQUEST';
export const ADD_QUANTITY_TO_CART_SUCCESS = 'ADD_QUANTITY_TO_CART_SUCCESS';
export const ADD_QUANTITY_TO_CART_FAILURE = 'ADD_QUANTITY_TO_CART_FAILURE';
export const SUBTRACT_QUANTITY_FROM_CART_REQUEST = 'SUBTRACT_QUANTITY_FROM_CART_REQUEST';
export const SUBTRACT_QUANTITY_FROM_CART_SUCCESS = 'SUBTRACT_QUANTITY_FROM_CART_SUCCESS';
export const SUBTRACT_QUANTITY_FROM_CART_FAILURE = 'SUBTRACT_QUANTITY_FROM_CART_FAILURE';
export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE";
export const UPDATE_CART_COUNT = 'UPDATE_CART_COUNT';

//wishlist
export const AUTH_CHECK_WISHLIST_REQUEST = "AUTH_CHECK_WISHLIST_REQUEST";
export const AUTH_CHECK_WISHLIST_SUCCESS = "AUTH_CHECK_WISHLIST_SUCCESS";
export const AUTH_CHECK_WISHLIST_FAILURE = "AUTH_CHECK_WISHLIST_FAILURE";
export const ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_FAILURE = "ADD_TO_WISHLIST_FAILURE";
export const REMOVE_FROM_WISHLIST_REQUEST = "REMOVE_FROM_WISHLIST_REQUEST";
export const REMOVE_FROM_WISHLIST_SUCCESS = "REMOVE_FROM_WISHLIST_SUCCESS";
export const REMOVE_FROM_WISHLIST_FAILURE = "REMOVE_FROM_WISHLIST_FAILURE";

// buynow
export const AUTH_CHECK_BUY_NOW_REQUEST = "AUTH_CHECK_BUY_NOW_REQUEST";
export const AUTH_CHECK_BUY_NOW_SUCCESS = "AUTH_CHECK_BUY_NOW_SUCCESS";
export const AUTH_CHECK_BUY_NOW_FAILURE = "AUTH_CHECK_BUY_NOW_FAILURE";
export const BUY_NOW_REQUEST = "BUY_NOW_REQUEST";
export const BUY_NOW_SUCCESS = "BUY_NOW_SUCCESS";
export const BUY_NOW_FAILURE = "BUY_NOW_FAILURE";
export const ADD_QUANTITY_IN_BUY_NOW_REQUEST = "ADD_QUANTITY_IN_BUY_NOW_REQUEST";
export const ADD_QUANTITY_IN_BUY_NOW_SUCCESS = "ADD_QUANTITY_IN_BUY_NOW_SUCCESS";
export const ADD_QUANTITY_IN_BUY_NOW_FAILURE = "ADD_QUANTITY_IN_BUY_NOW_FAILURE";
export const SUBTRACT_QUANTITY_FROM_BUY_NOW_REQUEST = "SUBTRACT_QUANTITY_FROM_BUY_NOW_REQUEST";
export const SUBTRACT_QUANTITY_FROM_BUY_NOW_SUCCESS = "SUBTRACT_QUANTITY_FROM_BUY_NOW_SUCCESS";
export const SUBTRACT_QUANTITY_FROM_BUY_NOW_FAILURE = "SUBTRACT_QUANTITY_FROM_BUY_NOW_FAILURE";
export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAILURE = "CHECKOUT_FAILURE";

// user address
export const AUTH_CHECK_USER_ADDRESS_REQUEST = "AUTH_CHECK_USER_ADDRESS_REQUEST";
export const AUTH_CHECK_USER_ADDRESS_SUCCESS = "AUTH_CHECK_USER_ADDRESS_SUCCESS";
export const AUTH_CHECK_USER_ADDRESS_FAILURE = "AUTH_CHECK_USER_ADDRESS_FAILURE";
export const USER_ADDRESS_SUBMIT_REQUEST = "USER_ADDRESS_SUBMIT_REQUEST";
export const USER_ADDRESS_SUBMIT_SUCCESS = "USER_ADDRESS_SUBMIT_SUCCESS";
export const USER_ADDRESS_SUBMIT_FAILURE = "USER_ADDRESS_SUBMIT_FAILURE";
export const AUTH_CHECK_EDIT_USER_ADDRESS_REQUEST = "AUTH_CHECK_EDIT_USER_ADDRESS_REQUEST";
export const AUTH_CHECK_EDIT_USER_ADDRESS_SUCCESS = "AUTH_CHECK_EDIT_USER_ADDRESS_SUCCESS";
export const AUTH_CHECK_EDIT_USER_ADDRESS_FAILURE = "AUTH_CHECK_EDIT_USER_ADDRESS_FAILURE";
export const USER_ADDRESS_EDIT_SUBMIT_REQUEST = "USER_ADDRESS_EDIT_SUBMIT_REQUEST";
export const USER_ADDRESS_EDIT_SUBMIT_SUCCESS = "USER_ADDRESS_EDIT_SUBMIT_SUCCESS";
export const USER_ADDRESS_EDIT_SUBMIT_FAILURE = "USER_ADDRESS_EDIT_SUBMIT_FAILURE";
export const USER_ADDRESS_DELETE_REQUEST = "USER_ADDRESS_DELETE_REQUEST";
export const USER_ADDRESS_DELETE_SUCCESS = "USER_ADDRESS_DELETE_SUCCESS";
export const USER_ADDRESS_DELETE_FAILURE = "USER_ADDRESS_DELETE_FAILURE";

// checkout
export const AUTH_CHECK_CHECKOUT_REQUEST = "AUTH_CHECK_CHECKOUT_REQUEST";
export const AUTH_CHECK_CHECKOUT_SUCCESS = "AUTH_CHECK_CHECKOUT_SUCCESS";
export const AUTH_CHECK_CHECKOUT_FAILURE = "AUTH_CHECK_CHECKOUT_FAILURE";
export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILURE = "PLACE_ORDER_FAILURE";
export const USER_ADDRESS_CALCULATIONS_REQUEST = "USER_ADDRESS_CALCULATIONS_REQUEST";
export const USER_ADDRESS_CALCULATIONS_SUCCESS = "USER_ADDRESS_CALCULATIONS_SUCCESS";
export const USER_ADDRESS_CALCULATIONS_FAILURE = "USER_ADDRESS_CALCULATIONS_FAILURE";

// user account
export const ACCOUNT_DETAILS_REQUEST = "ACCOUNT_DETAILS_REQUEST";
export const ACCOUNT_DETAILS_SUCCESS = "ACCOUNT_DETAILS_SUCCESS";
export const ACCOUNT_DETAILS_FAILURE = "ACCOUNT_DETAILS_FAILURE";
export const UPDATE_USER_PHOTO_REQUEST = "UPDATE_USER_PHOTO_REQUEST";
export const UPDATE_USER_PHOTO_SUCCESS = "UPDATE_USER_PHOTO_SUCCESS";
export const UPDATE_USER_PHOTO_FAILURE = "UPDATE_USER_PHOTO_FAILURE";
export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_FAILURE = "UPDATE_USER_DETAILS_FAILURE";
export const UPDATE_USER_PASSWORD_REQUEST = "UPDATE_USER_PASSWORD_REQUEST";
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS";
export const UPDATE_USER_PASSWORD_FAILURE = "UPDATE_USER_PASSWORD_FAILURE";


// orders
export const AUTH_CHECK_ORDERS_REQUEST = "AUTH_CHECK_ORDERS_REQUEST";
export const AUTH_CHECK_ORDERS_SUCCESS = "AUTH_CHECK_ORDERS_SUCCESS";
export const AUTH_CHECK_ORDERS_FAILURE = "AUTH_CHECK_ORDERS_FAILURE";
export const FETCH_ORDER_DETAILS_REQUEST = "FETCH_ORDER_DETAILS_REQUEST";
export const FETCH_ORDER_DETAILS_SUCCESS = "FETCH_ORDER_DETAILS_SUCCESS";
export const FETCH_ORDER_DETAILS_FAILURE = "FETCH_ORDER_DETAILS_FAILURE";
export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAILURE = "CANCEL_ORDER_FAILURE";
export const COMPLETE_ORDER_REQUEST = "COMPLETE_ORDER_REQUEST";
export const COMPLETE_ORDER_SUCCESS = "COMPLETE_ORDER_SUCCESS";
export const COMPLETE_ORDER_FAILURE = "COMPLETE_ORDER_FAILURE";
export const RATE_ORDER_REQUEST = "RATE_ORDER_REQUEST";
export const RATE_ORDER_SUCCESS = "RATE_ORDER_SUCCESS";
export const RATE_ORDER_FAILURE = "RATE_ORDER_FAILURE";
export const ORDER_RATING_CLOSE_FOREVER_REQUEST = "ORDER_RATING_CLOSE_FOREVER_REQUEST";
export const ORDER_RATING_CLOSE_FOREVER_SUCCESS = "ORDER_RATING_CLOSE_FOREVER_SUCCESS";
export const ORDER_RATING_CLOSE_FOREVER_FAILURE = "ORDER_RATING_CLOSE_FOREVER_FAILURE";

// sales
export const AUTH_CHECK_SALES_REQUEST = "AUTH_CHECK_SALES_REQUEST";
export const AUTH_CHECK_SALES_SUCCESS = "AUTH_CHECK_SALES_SUCCESS";
export const AUTH_CHECK_SALES_FAILURE = "AUTH_CHECK_SALES_FAILURE";
export const FETCH_SALE_DETAILS_REQUEST = "FETCH_SALE_DETAILS_REQUEST";
export const FETCH_SALE_DETAILS_SUCCESS = "FETCH_SALE_DETAILS_SUCCESS";
export const FETCH_SALE_DETAILS_FAILURE = "FETCH_SALE_DETAILS_FAILURE";

// deliveries
export const AUTH_CHECK_DELIVERIES_REQUEST = "AUTH_CHECK_DELIVERIES_REQUEST";
export const AUTH_CHECK_DELIVERIES_SUCCESS = "AUTH_CHECK_DELIVERIES_SUCCESS";
export const AUTH_CHECK_DELIVERIES_FAILURE = "AUTH_CHECK_DELIVERIES_FAILURE";
export const FETCH_DELIVERY_DETAILS_REQUEST = "FETCH_DELIVERY_DETAILS_REQUEST";
export const FETCH_DELIVERY_DETAILS_SUCCESS = "FETCH_DELIVERY_DETAILS_SUCCESS";
export const FETCH_DELIVERY_DETAILS_FAILURE = "FETCH_DELIVERY_DETAILS_FAILURE";

// user account tab
export const USER_ACCOUNT_TAB = "USER_ACCOUNT_TAB";

// admin
export const CHECK_AUTH_ADMIN_REQUEST = "CHECK_AUTH_ADMIN_REQUEST";
export const CHECK_AUTH_ADMIN_SUCCESS = "CHECK_AUTH_ADMIN_SUCCESS";
export const CHECK_AUTH_ADMIN_FAILURE = "CHECK_AUTH_ADMIN_FAILURE";
export const CHECK_AUTH_CREATE_DEMO_AD_REQUEST = "CHECK_AUTH_CREATE_DEMO_AD_REQUEST";
export const CHECK_AUTH_CREATE_DEMO_AD_SUCCESS = "CHECK_AUTH_CREATE_DEMO_AD_SUCCESS";
export const CHECK_AUTH_CREATE_DEMO_AD_FAILURE = "CHECK_AUTH_CREATE_DEMO_AD_FAILURE";
export const CREATE_DEMO_AD_REQUEST = "CREATE_DEMO_AD_REQUEST";
export const CREATE_DEMO_AD_SUCCESS = "CREATE_DEMO_AD_SUCCESS";
export const CREATE_DEMO_AD_FAILURE = "CREATE_DEMO_AD_FAILURE";
export const UPDATE_DEMO_AD_REQUEST = "UPDATE_DEMO_AD_REQUEST";
export const UPDATE_DEMO_AD_SUCCESS = "UPDATE_DEMO_AD_SUCCESS";
export const UPDATE_DEMO_AD_FAILURE = "UPDATE_DEMO_AD_FAILURE";
export const FETCH_DEMO_ADS_REQUEST = "FETCH_DEMO_ADS_REQUEST";
export const FETCH_DEMO_ADS_SUCCESS = "FETCH_DEMO_ADS_SUCCESS";
export const FETCH_DEMO_ADS_FAILURE = "FETCH_DEMO_ADS_FAILURE";
export const ADD_DEMO_AD_TO_USER_ACCOUNT_REQUEST = "ADD_DEMO_AD_TO_USER_ACCOUNT_REQUEST";
export const ADD_DEMO_AD_TO_USER_ACCOUNT_SUCCESS = "ADD_DEMO_AD_TO_USER_ACCOUNT_SUCCESS";
export const ADD_DEMO_AD_TO_USER_ACCOUNT_FAILURE = "ADD_DEMO_AD_TO_USER_ACCOUNT_FAILURE";
export const FETCH_DEMO_AD_REQUEST = "FETCH_DEMO_AD_REQUEST";
export const FETCH_DEMO_AD_SUCCESS = "FETCH_DEMO_AD_SUCCESS";
export const FETCH_DEMO_AD_FAILURE = "FETCH_DEMO_AD_FAILURE";
export const DEMO_AD_DELETE_REQUEST = "DEMO_AD_DELETE_REQUEST";
export const DEMO_AD_DELETE_SUCCESS = "DEMO_AD_DELETE_SUCCESS";
export const DEMO_AD_DELETE_FAILURE = "DEMO_AD_DELETE_FAILURE";

// local demo ads
export const FETCH_LISTED_DEMO_ADS_REQUEST = "FETCH_LISTED_DEMO_ADS_REQUEST";
export const FETCH_LISTED_DEMO_ADS_SUCCESS = "FETCH_LISTED_DEMO_ADS_SUCCESS";
export const FETCH_LISTED_DEMO_ADS_FAILURE = "FETCH_LISTED_DEMO_ADS_FAILURE";
export const DEMO_AD_ADD_TO_LIST_REQUEST = "DEMO_AD_ADD_TO_LIST_REQUEST";
export const DEMO_AD_ADD_TO_LIST_SUCCESS = "DEMO_AD_ADD_TO_LIST_SUCCESS";
export const DEMO_AD_ADD_TO_LIST_FAILURE = "DEMO_AD_ADD_TO_LIST_FAILURE";
export const DEMO_AD_REMOVE_FROM_LIST_REQUEST = "DEMO_AD_REMOVE_FROM_LIST_REQUEST";
export const DEMO_AD_REMOVE_FROM_LIST_SUCCESS = "DEMO_AD_REMOVE_FROM_LIST_SUCCESS";
export const DEMO_AD_REMOVE_FROM_LIST_FAILURE = "DEMO_AD_REMOVE_FROM_LIST_FAILURE";

// search result
export const SEARCH_RESULT_ADS_REQUEST = "SEARCH_RESULT_ADS_REQUEST";
export const SEARCH_RESULT_ADS_SUCCESS = "SEARCH_RESULT_ADS_SUCCESS";
export const SEARCH_RESULT_ADS_FAILURE = "SEARCH_RESULT_ADS_FAILURE";
export const SEARCH_RESULT_SHOPS_REQUEST = "SEARCH_RESULT_SHOPS_REQUEST";
export const SEARCH_RESULT_SHOPS_SUCCESS = "SEARCH_RESULT_SHOPS_SUCCESS";
export const SEARCH_RESULT_SHOPS_FAILURE = "SEARCH_RESULT_SHOPS_FAILURE";
export const SEARCH_RESULT_OF_SHOP_REQUEST = "SEARCH_RESULT_OF_SHOP_REQUEST";
export const SEARCH_RESULT_OF_SHOP_SUCCESS = "SEARCH_RESULT_OF_SHOP_SUCCESS";
export const SEARCH_RESULT_OF_SHOP_FAILURE = "SEARCH_RESULT_OF_SHOP_FAILURE";

// contact us
export const CONTACT_US_REQUEST = "CONTACT_US_REQUEST";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAILURE = "CONTACT_US_FAILURE";

// report
export const AD_REPORT_REQUEST = "AD_REPORT_REQUEST";
export const AD_REPORT_SUCCESS = "AD_REPORT_SUCCESS";
export const AD_REPORT_FAILURE = "AD_REPORT_FAILURE";
export const SHOP_REPORT_REQUEST = "SHOP_REPORT_REQUEST";
export const SHOP_REPORT_SUCCESS = "SHOP_REPORT_SUCCESS";
export const SHOP_REPORT_FAILURE = "SHOP_REPORT_FAILURE";

// update homepage
export const UPDATE_HOMEPAGE_TOP_SLIDER_REQUEST = "UPDATE_HOMEPAGE_TOP_SLIDER_REQUEST";
export const UPDATE_HOMEPAGE_TOP_SLIDER_SUCCESS = "UPDATE_HOMEPAGE_TOP_SLIDER_SUCCESS";
export const UPDATE_HOMEPAGE_TOP_SLIDER_FAILURE = "UPDATE_HOMEPAGE_TOP_SLIDER_FAILURE";
export const UPDATE_HOMEPAGE_SECOND_SLIDER_REQUEST = "UPDATE_HOMEPAGE_SECOND_SLIDER_REQUEST";
export const UPDATE_HOMEPAGE_SECOND_SLIDER_SUCCESS = "UPDATE_HOMEPAGE_SECOND_SLIDER_SUCCESS";
export const UPDATE_HOMEPAGE_SECOND_SLIDER_FAILURE = "UPDATE_HOMEPAGE_SECOND_SLIDER_FAILURE";
export const UPDATE_HOMEPAGE_LATEST_REQUEST = "UPDATE_HOMEPAGE_LATEST_REQUEST";
export const UPDATE_HOMEPAGE_LATEST_SUCCESS = "UPDATE_HOMEPAGE_LATEST_SUCCESS";
export const UPDATE_HOMEPAGE_LATEST_FAILURE = "UPDATE_HOMEPAGE_LATEST_FAILURE";
export const UPDATE_HOMEPAGE_SPECIAL_REQUEST = "UPDATE_HOMEPAGE_SPECIAL_REQUEST";
export const UPDATE_HOMEPAGE_SPECIAL_SUCCESS = "UPDATE_HOMEPAGE_SPECIAL_SUCCESS";
export const UPDATE_HOMEPAGE_SPECIAL_FAILURE = "UPDATE_HOMEPAGE_SPECIAL_FAILURE";
export const UPDATE_HOMEPAGE_FEATURED_REQUEST = "UPDATE_HOMEPAGE_FEATURED_REQUEST";
export const UPDATE_HOMEPAGE_FEATURED_SUCCESS = "UPDATE_HOMEPAGE_FEATURED_SUCCESS";
export const UPDATE_HOMEPAGE_FEATURED_FAILURE = "UPDATE_HOMEPAGE_FEATURED_FAILURE";
export const UPDATE_HOMEPAGE_SPANA_REQUEST = "UPDATE_HOMEPAGE_SPANA_REQUEST";
export const UPDATE_HOMEPAGE_SPANA_SUCCESS = "UPDATE_HOMEPAGE_SPANA_SUCCESS";
export const UPDATE_HOMEPAGE_SPANA_FAILURE = "UPDATE_HOMEPAGE_SPANA_FAILURE";
export const UPDATE_HOMEPAGE_SPANB_REQUEST = "UPDATE_HOMEPAGE_SPANB_REQUEST";
export const UPDATE_HOMEPAGE_SPANB_SUCCESS = "UPDATE_HOMEPAGE_SPANB_SUCCESS";
export const UPDATE_HOMEPAGE_SPANB_FAILURE = "UPDATE_HOMEPAGE_SPANB_FAILURE";
export const UPDATE_HOMEPAGE_SPANC_REQUEST = "UPDATE_HOMEPAGE_SPANC_REQUEST";
export const UPDATE_HOMEPAGE_SPANC_SUCCESS = "UPDATE_HOMEPAGE_SPANC_SUCCESS";
export const UPDATE_HOMEPAGE_SPANC_FAILURE = "UPDATE_HOMEPAGE_SPANC_FAILURE";
export const UPDATE_HOMEPAGE_TRENDING_REQUEST = "UPDATE_HOMEPAGE_TRENDING_REQUEST";
export const UPDATE_HOMEPAGE_TRENDING_SUCCESS = "UPDATE_HOMEPAGE_TRENDING_SUCCESS";
export const UPDATE_HOMEPAGE_TRENDING_FAILURE = "UPDATE_HOMEPAGE_TRENDING_FAILURE";
export const UPDATE_HOMEPAGE_BESTSELLERS_REQUEST = "UPDATE_HOMEPAGE_BESTSELLERS_REQUEST";
export const UPDATE_HOMEPAGE_BESTSELLERS_SUCCESS = "UPDATE_HOMEPAGE_BESTSELLERS_SUCCESS";
export const UPDATE_HOMEPAGE_BESTSELLERS_FAILURE = "UPDATE_HOMEPAGE_BESTSELLERS_FAILURE";

// Impose new changes
export const IMPOSE_NEW_CHANGES_REQUEST = "IMPOSE_NEW_CHANGES_REQUEST";
export const IMPOSE_NEW_CHANGES_SUCCESS = "IMPOSE_NEW_CHANGES_SUCCESS";
export const IMPOSE_NEW_CHANGES_FAILURE = "IMPOSE_NEW_CHANGES_FAILURE";

// Delivery Person Status
export const DELIVERY_PERSON_STATUS_REQUEST = "DELIVERY_PERSON_STATUS_REQUEST";
export const DELIVERY_PERSON_STATUS_SUCCESS = "DELIVERY_PERSON_STATUS_SUCCESS";
export const DELIVERY_PERSON_STATUS_FAILURE = "DELIVERY_PERSON_STATUS_FAILURE";
export const DELIVERY_PERSON_STATUS_CHANGE_REQUEST = "DELIVERY_PERSON_STATUS_CHANGE_REQUEST";
export const DELIVERY_PERSON_STATUS_CHANGE_SUCCESS = "DELIVERY_PERSON_STATUS_CHANGE_SUCCESS";
export const DELIVERY_PERSON_STATUS_CHANGE_FAILURE = "DELIVERY_PERSON_STATUS_CHANGE_FAILURE";